const STORAGE='zaad-state-v1';
const state={content:null,tracker:[false,false,false,false,false],tasbeeh:0,total:0,lastActivity:'',category:'all'};
const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'{}');Object.assign(state,saved);const r=await fetch('data/content.json');if(!r.ok)throw Error();state.content=await r.json();bind();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});window.addEventListener('online',()=>$('#connectionStatus').textContent='متصل');window.addEventListener('offline',()=>$('#connectionStatus').textContent='دون اتصال');}catch(e){$('#searchStatus').textContent='تعذر تحميل المحتوى المحلي.';}}
function save(){localStorage.setItem(STORAGE,JSON.stringify({...state,content:undefined}));}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#globalSearch').addEventListener('input',e=>search(e.target.value));$('#athkarCategory').addEventListener('change',e=>{state.category=e.target.value;renderAthkar();});$('#tasbeehButton').addEventListener('click',()=>{state.tasbeeh++;state.total++;state.lastActivity='آخر نشاط: التسبيح';save();renderTasbeeh();renderHome();});$('#resetTasbeeh').addEventListener('click',()=>{state.tasbeeh=0;save();renderTasbeeh();});}
function showView(view){document.querySelectorAll('[data-section]').forEach(e=>e.hidden=e.dataset.section!==view);document.querySelectorAll('.tab').forEach(e=>e.classList.toggle('active',e.dataset.view===view));if(view!=='home')window.scrollTo({top:0,behavior:'smooth'});}
function renderAll(){renderHome();renderSurahs();renderAthkar();renderHadith();renderTracker();renderTasbeeh();}
function renderHome(){const done=state.tracker.filter(Boolean).length;const pct=Math.round(done/state.tracker.length*100);$('#progressValue').textContent=pct+'%';$('#lastActivity').textContent=state.lastActivity||'لا يوجد نشاط محفوظ بعد';$('#connectionStatus').textContent=navigator.onLine?'متصل':'دون اتصال';$('#homeHighlights').innerHTML=[['القرآن',state.content.surahs.length+' سورة','بيانات السور فقط'],['الأذكار',state.content.athkar.length+' عناصر','حالة المراجعة ظاهرة'],['الحديث',state.content.hadith.length+' عناصر','المصدر مطلوب قبل النشر']].map(x=>`<article class="item"><b>${esc(x[0])}</b><div>${esc(x[1])}</div><small class="muted">${esc(x[2])}</small></article>`).join('');}
function renderSurahs(){const q=($('#globalSearch').value||'').trim();$('#surahList').innerHTML=state.content.surahs.filter(x=>!q||x.name.includes(q)).map(x=>`<article class="item"><div class="item-head"><b>${esc(x.id)}. ${esc(x.name)}</b><span class="status">${esc(x.type)} · ${esc(x.verses)} آية</span></div><small class="source">الجزء ${esc(x.juz)} · ${esc(x.source)}</small></article>`).join('')||'<p class="muted">لا توجد نتائج.</p>';}
function renderAthkar(){const list=state.content.athkar.filter(x=>state.category==='all'||x.category===state.category);$('#athkarList').innerHTML=list.map(x=>`<article class="item"><p class="quran-text">${esc(x.text)}</p><div class="item-head"><span class="source">التكرار: ${esc(x.count)} · ${esc(x.source)}</span><span class="status">${esc(x.status)}</span></div><div class="item-actions"><button class="mini" data-count="${esc(x.id)}">تسجيل تكرار</button></div></article>`).join('')||'<p class="muted">لا توجد أذكار.</p>';document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{state.lastActivity='آخر نشاط: الذكر '+b.dataset.count;save();renderHome();showToast('تم حفظ النشاط محليًا');});}
function renderHadith(){$('#hadithList').innerHTML=state.content.hadith.map(x=>`<article class="item"><div class="item-head"><b>${esc(x.title)}</b><span class="status">${esc(x.status)}</span></div><p>${esc(x.text)}</p><small class="source">${esc(x.source)}</small></article>`).join('');}
function renderTracker(){$('#trackerList').innerHTML=['صلاة الفجر','أذكار الصباح','قراءة القرآن','صلاة الظهر والعصر','أذكار المساء'].map((x,i)=>`<label class="tracker-item ${state.tracker[i]?'done':''}"><input type="checkbox" data-track="${i}" ${state.tracker[i]?'checked':''}>${esc(x)}</label>`).join('');document.querySelectorAll('[data-track]').forEach(c=>c.onchange=()=>{state.tracker[Number(c.dataset.track)]=c.checked;state.lastActivity='آخر نشاط: متابعة العبادات';save();renderTracker();renderHome();});$('#trackerPercentage').textContent=Math.round(state.tracker.filter(Boolean).length/state.tracker.length*100)+'%';}
function renderTasbeeh(){$('#tasbeehCount').textContent=state.tasbeeh;$('#tasbeehTotal').textContent=state.total;}
function search(q){const term=q.trim().toLowerCase();if(!term){$('#searchResults').hidden=true;$('#searchStatus').textContent='';renderSurahs();return;}const all=[...state.content.surahs.map(x=>({type:'سورة',title:x.name,detail:x.verses+' آية'})),...state.content.athkar.map(x=>({type:'ذكر',title:x.text,detail:x.source})),...state.content.hadith.map(x=>({type:'حديث',title:x.title,detail:x.source}))];const result=all.filter(x=>(x.title+' '+x.detail).toLowerCase().includes(term));$('#searchResults').hidden=false;$('#searchResults').innerHTML='<h2>نتائج البحث</h2>'+(result.length?result.map(x=>`<article class="item"><b>${esc(x.type)}: ${esc(x.title)}</b><small class="source">${esc(x.detail)}</small></article>`).join(''):'<p class="muted">لم نجد نتائج. جرّب كلمة أخرى.</p>');$('#searchStatus').textContent=`${result.length} نتيجة محلية`;renderSurahs();}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),2200);}
init();
